# Generated by Django 4.1.3 on 2022-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='user date of birth', null=True, verbose_name='Date of birth'),
        ),
    ]
