# Generated by Django 4.1.3 on 2022-11-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('TRANSFER', 'TRANSFER'), ('TRANSFER_SUCCESSFULL', 'TRANSFER_SUCCESSFULL'), ('TRANSFER_REJECTED', 'TRANSFER_REJECTED'), ('WITHDRAW', 'WITHDRAW'), ('WITHDRAW_REJECTED', 'WITHDRAW_REJECTED'), ('WITHDRAW_CANCEL', 'WITHDRAW_CANCEL'), ('WITHDRAW_SUCCESSFULL', 'WITHDRAW_SUCCESSFULL'), ('WITHDRAW_CANCEL', 'WITHDRAW_CANCEL'), ('ACCOUNT_EMPTY', 'ACCOUNT_EMPTY'), ('ALERT', 'ALERT')], default='NORMAL', max_length=20),
        ),
    ]
