# Generated by Django 4.1.3 on 2022-11-30 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(help_text='user id', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('CANCEL', 'CANCEL'), ('ACCEPTED', 'ACCEPTED')], default='PENDING', help_text="state here represents the different state of withdraw wich can either be 'pending','cancel','accepted','rejected'", max_length=20),
        ),
    ]
