# Generated by Django 4.1.3 on 2022-12-03 21:16

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_account_user_alter_withdraw_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin_code',
            field=models.CharField(default='00000', help_text='pin code use to authorize transaction in a user account', max_length=5, validators=[core.validators.validate_pin_code]),
        ),
        migrations.AlterField(
            model_name='transactioncharge',
            name='charge',
            field=models.FloatField(default=0, help_text='charge in % example 0.02 '),
        ),
    ]
