# Generated by Django 4.1.3 on 2022-12-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_account_pin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=8, default=0, help_text='User account balance', max_digits=20),
        ),
    ]
