# Generated by Django 4.1.3 on 2022-12-04 07:54

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='agent',
            field=models.ForeignKey(help_text='the account id of the user from which the money is withdraw from', on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='core.account', validators=[core.validators.IsAgent]),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='withdraw_from',
            field=models.ForeignKey(help_text='the account id of the agent making the transaction', on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_from', to='core.account'),
        ),
    ]
