# Generated by Django 4.1.3 on 2022-12-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_withdraw_agent_alter_withdraw_withdraw_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='charge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.transactioncharge'),
            preserve_default=False,
        ),
    ]
